# Generated by Django 4.2.5 on 2023-10-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_category_image_serviceimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimages',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.service'),
        ),
    ]
